import numpy as np
import matplotlib.pyplot as plt
h = np.array([5,6,0,0,9,4,6])
x = np.array([1,0,3,2,6,7,9,4,6,4])
y = np.convolve(x, h)
print("y[n]1 =", y)
plt.stem(y)
plt.xlim(left=0)
plt.ylim(bottom=0)
plt.title("Convolución y[n]1")
plt.xlabel("n")
plt.ylabel("y[n]1")
plt.show()
z = np.array([5,6,0,0,9,4,7])
m = np.array([1,1,1,8,1,6,8,2,0,1])
y = np.convolve(m, z)
print("y[n]2 =", y)
plt.stem(y)
plt.xlim(left=0)
plt.ylim(bottom=0)
plt.title("Convolución y[n]2")
plt.xlabel("n")
plt.ylabel("y[n]2")
plt.show()
a = np.array([5,6,0,0,9,1,8])
b = np.array([1,0,6,9,7,2,0,7,2,1])
y = np.convolve(b, a)
print("y[n]3 =", y)
plt.stem(y)
plt.xlim(left=0)
plt.ylim(bottom=0)
plt.title("Convolución y[n]3")
plt.xlabel("n")
plt.ylabel("y[n]")
plt.show()